### ISSUE TITLE
Work inbox changing views 

### ISSUE THREAD

**Issue by jives95** [sives/Plio#144] opened 2016-09-25 18:22 UTC
'My current work' and other options such as 'team current work' in the header should be a different color than white to show that it is selectable, it is difficult to know it is a button where you can switch views. 

Also next to each different view have the total number of items in each, e.g. my current work has 2 items and team work has 7. So have to the right of each view on the dropdown header have a icon with the total number of items found in each view.

**Comment by sives** [comment] 2016-10-03 12:40
Jack has already made this enhancement in the Plio UI prototype.  He's just made the blue chevron bigger and made it light blue instead of white.

**Comment by Praxie** [comment] 2016-10-05 09:39
@sives could this issue be resolved now?
What about a second part? Is it required?
"Also next to each different view have the total number of items in each, e.g. my current work has 2 items and team work has 7. So have to the right of each view on the dropdown header have a icon with the total number of items found in each view."

**Comment by sives** [comment] 2016-10-05 10:12
Here's a good design solution, but let's allocate this to Milestone 2d.

![e08279c87290a5b451ee2cb4538e806e](https://cloud.githubusercontent.com/assets/2330529/19109299/97a99042-8aec-11e6-8f15-9a3565725e1c.png)

**Comment by sives** [comment] 2016-10-05 11:16
This issue is a duplicate of issue 170, so I'm closing this issue

**Closed by sives** 2016-10-05 11:16 UTC
Labels: enhancement, UI enhancement
