### ISSUE TITLE
List view layout in Risk screen

### ISSUE THREAD

**Issue by sives** [sives/Plio#137] opened 2016-09-21 15:18 UTC
The List view item panel design in the Risks screen is a bit different from that in the Non-conformities screen - there should be a coloured square box with rounded corners on the left hand side of the item panel, containing the risk score.

Here is the UI prototype for the Risks screen:
http://ui2.isometrica.io/ui1/risk-register.html

![screen shot 2016-09-21 at 16 20 09](https://cloud.githubusercontent.com/assets/2330529/18717281/55c92230-8017-11e6-8781-e2d3704f8bec.png)

**Comment by sives** [comment] 2016-10-10 15:43
I tried to edit the "Loss of Galaxy service" risk in the Plio Ltd organization and it wouldn't let me.  I tried to delete this risk and it wouldn't let me

**Comment by sives** [comment] 2016-10-10 15:48
The Close button at the top gets frozen on "Saving...."

**Comment by sives** [comment] 2016-10-10 15:49
I can remove the entire Risk, but I can't remove the individual risk score (or edit it)

**Comment by Praxie** [comment] 2016-10-11 11:43
@sives The issue is resolved in the current release.

**Closed** 2016-10-11 12:52 UTC
Labels: bug, resolved

**Comment by Praxie** [comment] 2016-10-11 14:52
Before:
![screen shot 2016-10-11 at 5 52 25 pm](https://cloud.githubusercontent.com/assets/2095940/19275170/850b3eec-8fdb-11e6-83ff-6536d7eb3dd9.png)
After:
![screen shot 2016-10-11 at 5 52 30 pm](https://cloud.githubusercontent.com/assets/2095940/19275172/865d7026-8fdb-11e6-93cf-116ae6f23599.png)
